Repository Feather-Flock/birds-ui, pull requests merged in 2022-08, with the labels that each got.

#2 Add Cypress and configure circleCI to run cypress tests
  .circleci/config.yml
  cypress.config.js
  cypress/e2e/app.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/videos/app.cy.js.mp4
  package-lock.json
  package.json
Labels: enhancement

#16 Feature/component structure
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/EventCard/EventCard.css
  src/Components/EventCard/EventCard.js
  src/Components/EventForm/EventForm.css
  src/Components/EventForm/EventForm.js
  src/Components/EventModal/EventModal.css
  src/Components/EventModal/EventModal.js
  src/Components/Events/Events.css
  src/Components/Events/Events.js
  src/Components/UserProfile/UserProfile.css
  src/Components/UserProfile/UserProfile.js
  src/index.js
  src/logo.svg
  src/queries.js
  src/reportWebVitals.js
Labels: documentation

#22 Enhancement/dashboard buildout
  .env
  package-lock.json
  src/Components/App/App.js
  src/Components/Dashboard/Dashboard.css
  src/Components/Dashboard/Dashboard.js
  src/Components/EventCard/EventCard.css
  src/Components/EventCard/EventCard.js
  src/Components/Events/Events.js
  src/queries.js
Labels: enhancement, front end

#23 Feature/user profile
  public/index.html
  src/Components/App/App.js
  src/Components/UserProfile/UserProfile.css
  src/Components/UserProfile/UserProfile.js
Labels: front end

#25 fix css in create event form to correct div placement on other pages
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/EventForm/EventForm.css
  src/Components/EventForm/EventForm.js
  src/Components/UserProfile/UserProfile.css
Labels: front end, refactor

#35 Changed how the apollo client is being created with uri
  src/Components/App/App.js
Labels: bug, front end
