Repository Feather-Flock/birds-ui, pull requests merged in 2022-09, with the labels that each got.

#37 Feature/carousel
  package-lock.json
  package.json
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Dashboard/Dashboard.css
  src/Components/Dashboard/Dashboard.js
  src/Components/DashboardList/DashboardList.css
  src/Components/DashboardList/DashboardList.js
  src/Components/EventCard/EventCard.css
  src/Components/EventCard/EventCard.js
  src/Components/EventForm/EventForm.css
  src/Components/EventModal/EventModal.css
  src/Components/Events/Events.css
  src/Components/Events/Events.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/Components/UserProfile/UserProfile.css
  src/Components/UserProfile/UserProfile.js
  src/index.js
  src/queries.js
Labels: bug, enhancement, front end, refactor

#38 Feature/UUID
  package-lock.json
  package.json
  src/Components/Events/Events.js
  src/queries.js
Labels: front end

#39 Enhancement/user query
  src/Components/Dashboard/Dashboard.js
  src/Components/DashboardList/DashboardList.js
  src/Components/EventCard/EventCard.js
  src/Components/EventModal/EventModal.js
  src/Components/Events/Events.js
  src/Components/UserProfile/UserProfile.css
  src/Components/UserProfile/UserProfile.js
  src/queries.js
Labels: enhancement, front end, refactor

#41 Enhancement/rsvp mutation
  src/Components/Dashboard/Dashboard.js
  src/Components/DashboardList/DashboardList.js
  src/Components/EventModal/EventModal.js
  src/Components/Events/Events.css
  src/Components/Events/Events.js
  src/queries.js
Labels: enhancement, front end, refactor

#43 Feature/event form map
  src/Components/Dashboard/Dashboard.js
  src/Components/EventForm/EventForm.css
  src/Components/EventForm/EventForm.js
  src/queries.js
Labels: enhancement, front end

#44 add user created events to profile page
  src/Components/UserProfile/UserProfile.js
  src/queries.js
Labels: enhancement, front end

#48 Enhancement/implement usecontext
  src/Components/App/App.js
  src/Components/Dashboard/Dashboard.js
  src/Components/DashboardList/DashboardList.js
  src/Components/UserProfile/UserProfile.js
  src/Context/UserContext.js
  src/index.js
  src/queries.js
Labels: enhancement, front end, refactor

#50 Refactor/profile view
  src/Components/EventModal/EventModal.js
  src/Components/UserProfile/UserProfile.js
Labels: front end, user story, UX/UI

#53 add amount of guests rsvpd to modal
  src/Components/Dashboard/Dashboard.js
  src/Components/EventModal/EventModal.js
Labels: enhancement, front end, user story, UX/UI

#62 Enhancement/delete event
  src/Components/App/App.js
  src/Components/EventCard/EventCard.css
  src/Components/EventCard/EventCard.js
  src/Components/EventForm/EventForm.js
  src/Components/Events/Events.js
  src/Components/UserProfile/UserProfile.js
  src/queries.js
Labels: enhancement, front end, UX/UI

#67 Enhancement/footer
  src/Components/App/App.js
  src/Components/Footer/Footer.css
  src/Components/Footer/Footer.js
Labels: enhancement, front end

#72 correct delete event location of trashcan
  src/Components/UserProfile/UserProfile.js
Labels: bug, front end

#74 Update circleCI config to work with heroku
  .circleci/config.yml
  .gitignore
  cypress/e2e/Dashboard.cy.js
  cypress/fixtures/user.json
  cypress/videos/app.cy.js.mp4
Labels: bug, front end, refactor

#73 Refactor/eventcard layout
  package-lock.json
  package.json
  src/Components/EventCard/EventCard.css
  src/Components/EventCard/EventCard.js
  src/Components/EventCard/EventCard.scss
  src/Components/EventModal/EventModal.css
  src/Components/EventModal/EventModal.js
  src/Components/Events/Events.css
  src/Components/Events/Events.js
Labels: front end

#76 Feature/select
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/Dashboard/Dashboard.css
  src/Components/Dashboard/Dashboard.js
  src/Components/EventModal/EventModal.js
  src/Components/SelectDropdown/SelectDropdown.js
  src/queries.js
Labels: front end, user story, UX/UI

#79 Refactor/general refactor
  src/Components/App/App.js
  src/Components/Dashboard/Dashboard.css
  src/Components/Dashboard/Dashboard.js
  src/Components/DashboardList/DashboardList.css
  src/Components/DashboardList/DashboardList.js
  src/Components/EventCard/EventCard.js
  src/Components/EventForm/EventForm.js
  src/Components/EventModal/EventModal.js
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Components/SelectDropdown/SelectDropdown.js
  src/Components/UserProfile/UserProfile.js
Labels: bug, front end, refactor

#80 Testing/dashboard
  cypress/e2e/Dashboard.cy.js
  cypress/fixtures/user.json
  package-lock.json
Labels: front end

#83 Testing/dashboardlist
  cypress/e2e/DashboardList.cy.js
  cypress/fixtures/event.json
  cypress/utils/graphql-test-utils.js
  package-lock.json
Labels: front end

#86 Testing/dashboardv2
  cypress/e2e/Dashboard.cy.js
  cypress/e2e/DashboardList.cy.js
  cypress/e2e/EventModal.cy.js
  cypress/e2e/UserProfile.cy.js
  cypress/e2e/app.cy.js
  src/utils.js
Labels: documentation, enhancement, front end

#87 Fix/event form bug
  src/Components/App/App.js
  src/Components/EventForm/EventForm.js
  src/queries.js
Labels: bug

#85 add loading page to modal
  src/Components/App/App.js
  src/Components/EventModal/EventModal.js
  src/Components/LoadingPage/LoadingPage.css
  src/Components/LoadingPage/LoadingPage.js
Labels: front end, UX/UI

#84 Update README.md
  README.md
  cypress/fixtures/user.json
Labels: enhancement, front end

#92 Bug/bugfix
  .gitignore
  cypress/e2e/EventForm.cy.js
  cypress/videos/app.cy.js.mp4
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/EventCard/EventCard.js
  src/Components/EventForm/EventForm.css
  src/Components/Events/Events.js
  src/Components/Footer/Footer.css
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/Diversitytree.jpeg
  src/FlamingoFam.jpg
  src/LGBTfamily.jpeg
  src/rainbowbackground.jpg
  src/rainbowheart.jpeg
Labels: bug, front end, refactor

#95 Enhancement/error
  src/Components/App/App.js
  src/Components/Error/error.css
  src/Components/Error/index.js
  src/Components/EventModal/EventModal.js
  src/Components/UserProfile/UserProfile.js
Labels: enhancement, front end

#99 Feature/responsiveness small phone
  src/BirdFlock.png
  src/Components/App/App.css
  src/Components/Dashboard/Dashboard.css
  src/Components/DashboardList/DashboardList.css
  src/Components/EventForm/EventForm.css
  src/Components/EventForm/EventForm.js
  src/Components/Events/Events.css
  src/Components/Nav/Nav.css
Labels: enhancement

#110 Feature/add dummy data
  cypress/e2e/EventForm.cy.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/Components/UserProfile/UserProfile.js
  src/identityTags.js
  src/zipcodes.js
Labels: enhancement

#111 Feature/edit user profile
  cypress/e2e/Dashboard.cy.js
  cypress/e2e/DashboardList.cy.js
  cypress/e2e/UserProfile.cy.js
  package-lock.json
  src/Components/App/App.js
  src/Components/EventCard/EventCard.js
  src/Components/EventForm/EventForm.css
  src/Components/Nav/Nav.js
  src/Components/UpdateUserProfile/UpdateUserProfile.css
  src/Components/UpdateUserProfile/UpdateUserProfile.js
  src/Components/UserProfile/UserProfile.css
  src/Components/UserProfile/UserProfile.js
  src/identityTags.js
  src/zipcodes.js
Labels: documentation, enhancement, front end

#112 Update queries
  cypress/e2e/EventForm.cy.js
  src/Components/Nav/Nav.js
  src/Components/UpdateUserProfile/UpdateUserProfile.js
  src/queries.js
Labels: enhancement, front end
